---
development:
  cloud_name: karoid
  api_key: '889375523648575'
  api_secret: div6-V5ab0zaNhr6R7XM75k3Duc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: karoid
  api_key: '889375523648575'
  api_secret: div6-V5ab0zaNhr6R7XM75k3Duc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: karoid
  api_key: '889375523648575'
  api_secret: div6-V5ab0zaNhr6R7XM75k3Duc
  enhance_image_tag: true
  static_image_support: false
