# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7dd421b8561ab166aa20be06c788f404e359b44c8fb13434c7a4c57277cfea366b27ce104614d194ebf1326dcee4bc5a56d79fb4ccf902c0348867ef117d4565

test:
  secret_key_base: eea9c3257a2c193a8a54a0c6ae6645f85b698298b8ac8f833652d663ca2c846ae280450aed5740d41002e0a8c3e95ac75fde76978f6a733dfc407827ae1c4edb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
